version: "3.8"

services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb-log
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data


volumes:
  couchdb_data:
